#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Medik                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Chceš študovať medicínu na UPJŠ v Košiciach? Appka Medik ťa pripraví na prijímačky efektívne a rýchlo. Otázky a odpovede sú garantované Lekárskou fakultou UPJŠ.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Maros Petrus
your_link                                 :
your_city                                 : Kosice
email_address                             : maros.petrus@gmail.com
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Štúdium
    description                           : Nauč sa s Medikom všetky modelové otázky na prijímačky na medicínu na Lekársku fakultu UPJŠ v Košiciach
    fontawesome_icon_name                 :

  - title                                 : Test
    description                           : Vyskúšaj si simuláciu prijímačkového testu vďaka algoritmu, ktorý pre teba vygeneruje otázky za rovnakých podmienok
    fontawesome_icon_name                 :

  - title                                 : Nebifli sa
    description                           : S Medikom sa otázky nemusíš bifliť. Medik ti každú odpoveď vysvetlí, aby si jej rozumel.
    fontawesome_icon_name                 :



# Theme Settings
topbar_color                              : "#54BB70"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#54BB70"
cover_overlay_transparency                : 1

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
